name: Build Lambda Layer

on:
  # push:
  #   branches:
  #     - master  # Triggers on pushes to the master branch
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python Version'
        required: true
        type: number
        default: 3.10
      layer_file:
        description: 'Layer File'
        required: true
        type: string

env:
  layer_name: InvGen
  bucket_name: jack-invoice-gen
  bucket_uri: s3://jack-invoice-gen

permissions:
  id-token: write
  contents: read

jobs:
  build-lambda-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: happysad2/invoice_generator
          ref: master

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2  # Using v2 for stable functionality
        with:
          role-to-assume: arn:aws:iam::664908640219:role/GitHubActionsDeployRole
          role-session-name: GitHubActionsBuildLambdaLayer
          aws-region: ap-southeast-2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install dependencies and package
        run: |
          mkdir python
          pip install -r requirements/layer_${{ inputs.layer_file }}.txt -t python
          zip --quiet -r ${{ env.layer_name }}_${{ inputs.layer_file }}.zip python

      - name: Upload to S3 and publish layer
        run: |
          aws s3 cp ${{ env.layer_name }}_${{ inputs.layer_file }}.zip ${{ env.bucket_uri }}/${{ env.layer_name }}_${{ inputs.layer_file }}.zip
          aws lambda publish-layer-version --layer-name ${{ env.layer_name }}_${{ inputs.layer_file }} --content S3Bucket=${{ env.bucket_name }},S3Key=${{ env.layer_name }}_${{ inputs.layer_file }}.zip --compatible-runtimes python${{ inputs.python_version }}
