name: Deploy Lambda Function

on:
  push:
    branches:
      - master  # Set this to the branch from which you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Upgraded to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Assuming v4 is available and it's the latest
        with:
          node-version: '20'  # Using Node.js v20

      - name: Install dependencies
        run: |
          npm install

      - name: Package Lambda function
        run: |
          zip -r function.zip .  # Zip all files in the current directory

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'  # Specify your Lambda function's region
        run: |
          aws lambda update-function-code --function-name InvGen --zip-file fileb://function.zip --publish
