name: Build Lambda Layer

on:
  push:
    branches:
      - master  # Triggers on pushes to the master branch
  workflow_dispatch:  # Allows manual triggering from the GitHub UI
    inputs:
      python_version:
        description: 'Python Version'
        required: true
        type: number
        default: 3.10
      layer_file:
        description: 'Layer File'
        required: true
        type: string

env:
  layer_name: InvGen
  bucket_name: jack-invoice-gen
  bucket_uri: s3://jack-invoice-gen
  PYTHON_RUNTIME: 'python${{ github.event.inputs.python_version }}'

permissions:
  id-token: write
  contents: read

jobs:
  build-lambda-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: happysad2/invoice_generator
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python_version }}

      - name: Install dependencies and package
        run: |
          mkdir python
          pip install -r requirements/layer_${{ github.event.inputs.layer_file }}.txt -t python
          zip --quiet -r ${ENV:LAYER_NAME}_${ENV:LAYER_FILE}.zip python

      - name: Upload to S3
        run: |
          aws s3 cp ${ENV:LAYER_NAME}_${ENV:LAYER_FILE}.zip ${{ env.bucket_uri }}/${{ env.layer_name }}_${{ github.event.inputs.layer_file }}.zip

      - name: Publish Layer
        run: |
          aws lambda publish-layer-version --layer-name ${{ env.layer_name }}_${{ github.event.inputs.layer_file }} --content S3Bucket=${{ env.bucket_name }},S3Key=${{ env.layer_name }}_${{ github.event.inputs.layer_file }}.zip --compatible-runtimes ${{ env.PYTHON_RUNTIME }}

      - name: Debug Runtime
        run: echo "Runtime to be used: ${{ env.PYTHON_RUNTIME }}"
