name: build-lambda-layer

on:
  push:
    branches:
      - master  # Set this to the branch from which you want to deploy
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python Version'
        required: true
        type: number
        default: 3.10
      layer_file:
        description: 'Layer File'
        required: true
        type: string

env:
  layer_name: InvGen
  bucket_name: jack-invoice-gen
  bucket_uri: s3://jack-invoice-gen

permissions:
  id-token: write
  contents: read

jobs:
  build-lambda-layer:
    runs-on: ubuntu-latest
    env:
      PYTHON_RUNTIME: 'python${{ format('3.{0}', inputs.python_version % 1 * 10) }}'  # Ensures proper formatting

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: happysad2/invoice_generator
          ref: master

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::664908640219:role/GitHubActionsDeployRole
          role-session-name: GitHubActionsBuildLambdaLayer
          aws-region: ap-southeast-2

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Zip it all up and upload to S3
        run: |
          mkdir python
          pip install -r requirements/layer_${{ inputs.layer_file }}.txt -t python
          zip --quiet -r ${{ env.layer_name }}_${{ inputs.layer_file }}.zip python
          aws s3 cp ${{ env.layer_name }}_${{ inputs.layer_file }}.zip ${{ env.bucket_uri }}
          aws lambda publish-layer-version --layer-name ${{ env.layer_name }}_${{ inputs.layer_file }} --content S3Bucket=${{ env.bucket_name }},S3Key=${{ env.layer_name }}_${{ inputs.layer_file }}.zip --compatible-runtimes ${{ env.PYTHON_RUNTIME }}
